
AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance for VPC2 stack

Parameters:
  KeyName:
    Description: Key name for EC2
    Type: String

  Ec2AmiId:
    Description: EC2 AMI ID
    Type: String

  T2InstanceType:
    Description: EC2 instance type
    Type: String  

Resources:
  
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref Ec2AmiId
      InstanceType: !Ref T2InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces:
       
        - DeleteOnTermination: true
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
          SubnetId:
            !ImportValue
              'testVPC2stack-PrivateSubnet2'
      Tags:
        - Key: "Name"
          Value: "Nivas.Rajendran.labs-instance"
        - Key: "user"
          Value: "Nivas.Rajendran.labs"
        - Key: "stelligent-u-lesson"
          Value: "4.2"
        - Key: "stelligent-u-lab"
          Value: "4.2.2"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for VPC
      GroupName: EC2-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "Nivas.Rajendran.labs-sg"
        - Key: "user"
          Value: "Nivas.Rajendran.labs"
        - Key: "stelligent-u-lesson"
          Value: "4.2"
        - Key: "stelligent-u-lab"
          Value: "4.2.2"
      VpcId:
        !ImportValue
          'testVPC2stack-VPC2'

  

Outputs:
  Ec2InstanceId:
    Value: !Ref Ec2Instance
    Export:
      Name: !Sub ${AWS::StackName}-Ec2InstanceId

  Ec2PrivateId:
    Value: !GetAtt Ec2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-Ec2PrivateId