AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stelligent-u-nivas
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: LifeCycleRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            NoncurrentVersionExpiration:
                NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
        - Key: "stelligent-u-lesson"
          Value: "2.3"
        - Key: "stelligent-u-lab"
          Value: "2.3.3"
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            AWS: "Nivas.Rajendran.labs"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource:
            - !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
        Statement:
          Effect: "Allow"
          Principal: "*"
          Action:
            - "s3:GetObject"
          Resource:
            - !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
        Statement:
        - Action:
            - 's3:PutObject'
          Effect: Allow
          Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref Bucket
              - /*
          Principal: '*'
          Condition:
            StringLike:
              's3:x-amz-server-side-encryption':
                - 'AES256'
              's3:x-amz-server-side-encryption-aws-kms-key-id':
                - 'aws:kms'
                