AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles creation

Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  IamRole2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'iam:Get*'
              - 'iam:List*'
            Resource: '*'
      PolicyName: ReadOnlyPolicy
      Roles:
        - !Ref IamRole
        - !Ref IamRole2